#!/bin/sh /etc/rc.common
START=95
USE_PROCD=1

start_service() {
  procd_open_instance
  procd_set_param command /bin/sh -c "/usr/sbin/ec25_gps_read.sh /dev/ttyUSB3 /var/run/gateway_location.json || exit 0"
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}
